UPDATE crops SET image_url = 'assets/images/crops/rice.jpg' WHERE crop_name = 'Rice';
UPDATE crops SET image_url = 'assets/images/crops/wheat.jpg' WHERE crop_name = 'Wheat';
UPDATE crops SET image_url = 'assets/images/crops/maize.jpg' WHERE crop_name = 'Maize';
UPDATE crops SET image_url = 'assets/images/crops/sorghum.jpeg' WHERE crop_name = 'Sorghum';
UPDATE crops SET image_url = 'assets/images/crops/pearl_millet.jpg' WHERE crop_name = 'Pearl Millet';
UPDATE crops SET image_url = 'assets/images/crops/finger_millet.jpg' WHERE crop_name = 'Finger Millet';
UPDATE crops SET image_url = 'assets/images/crops/barley.jpg' WHERE crop_name = 'Barley';
UPDATE crops SET image_url = 'assets/images/crops/chickpeas.jpg' WHERE crop_name = 'Chickpeas';
UPDATE crops SET image_url = 'assets/images/crops/pigeon_peas.jpg' WHERE crop_name = 'Pigeon Peas';
UPDATE crops SET image_url = 'assets/images/crops/black_gram_urad.jpg' WHERE crop_name = 'Black Gram (Urad)';
UPDATE crops SET image_url = 'assets/images/crops/green_gram_moong.jpg' WHERE crop_name = 'Green Gram (Moong)';
UPDATE crops SET image_url = 'assets/images/crops/lentils.jpg' WHERE crop_name = 'Lentils';
UPDATE crops SET image_url = 'assets/images/crops/soybean.jpg' WHERE crop_name = 'Soybean';
UPDATE crops SET image_url = 'assets/images/crops/peanuts.jpg' WHERE crop_name = 'Peanuts';
UPDATE crops SET image_url = 'assets/images/crops/mustard.jpg' WHERE crop_name = 'Mustard';
UPDATE crops SET image_url = 'assets/images/crops/sunflower.jpg' WHERE crop_name = 'Sunflower';
UPDATE crops SET image_url = 'assets/images/crops/safflower.jpg' WHERE crop_name = 'Safflower';
UPDATE crops SET image_url = 'assets/images/crops/sesame.jpg' WHERE crop_name = 'Sesame';
UPDATE crops SET image_url = 'assets/images/crops/linseed.jpg' WHERE crop_name = 'Linseed';
UPDATE crops SET image_url = 'assets/images/crops/castor.jpg' WHERE crop_name = 'Castor';
UPDATE crops SET image_url = 'assets/images/crops/sugarcane.jpg' WHERE crop_name = 'Sugarcane';
UPDATE crops SET image_url = 'assets/images/crops/cotton.jpg' WHERE crop_name = 'Cotton';
UPDATE crops SET image_url = 'assets/images/crops/jute.jpg' WHERE crop_name = 'Jute';
UPDATE crops SET image_url = 'assets/images/crops/tobacco.jpg' WHERE crop_name = 'Tobacco';
UPDATE crops SET image_url = 'assets/images/crops/tea.jpg' WHERE crop_name = 'Tea';
UPDATE crops SET image_url = 'assets/images/crops/coffee.jpg' WHERE crop_name = 'Coffee';
UPDATE crops SET image_url = 'assets/images/crops/rubber.jpeg' WHERE crop_name = 'Rubber';
UPDATE crops SET image_url = 'assets/images/crops/coconut.jpg' WHERE crop_name = 'Coconut';
UPDATE crops SET image_url = 'assets/images/crops/cashew.jpg' WHERE crop_name = 'Cashew';
UPDATE crops SET image_url = 'assets/images/crops/areca_nut.jpg' WHERE crop_name = 'Areca Nut';
UPDATE crops SET image_url = 'assets/images/crops/black_pepper.jpg' WHERE crop_name = 'Black Pepper';
UPDATE crops SET image_url = 'assets/images/crops/cardamom.jpg' WHERE crop_name = 'Cardamom';
UPDATE crops SET image_url = 'assets/images/crops/clove.jpg' WHERE crop_name = 'Clove';
UPDATE crops SET image_url = 'assets/images/crops/turmeric.jpg' WHERE crop_name = 'Turmeric';
UPDATE crops SET image_url = 'assets/images/crops/ginger.jpg' WHERE crop_name = 'Ginger';
UPDATE crops SET image_url = 'assets/images/crops/garlic.jpg' WHERE crop_name = 'Garlic';
UPDATE crops SET image_url = 'assets/images/crops/coriander.jpg' WHERE crop_name = 'Coriander';
UPDATE crops SET image_url = 'assets/images/crops/cumin.jpg' WHERE crop_name = 'Cumin';
UPDATE crops SET image_url = 'assets/images/crops/fennel.jpg' WHERE crop_name = 'Fennel';
UPDATE crops SET image_url = 'assets/images/crops/mango.jpg' WHERE crop_name = 'Mango';
UPDATE crops SET image_url = 'assets/images/crops/banana.jpg' WHERE crop_name = 'Banana';
UPDATE crops SET image_url = 'assets/images/crops/citrus.jpg' WHERE crop_name = 'Citrus';
UPDATE crops SET image_url = 'assets/images/crops/apple.jpg' WHERE crop_name = 'Apple';
UPDATE crops SET image_url = 'assets/images/crops/papaya.jpeg' WHERE crop_name = 'Papaya';
UPDATE crops SET image_url = 'assets/images/crops/grapes.jpg' WHERE crop_name = 'Grapes';
UPDATE crops SET image_url = 'assets/images/crops/potato.jpg' WHERE crop_name = 'Potato';
UPDATE crops SET image_url = 'assets/images/crops/tomato.jpg' WHERE crop_name = 'Tomato';
UPDATE crops SET image_url = 'assets/images/crops/onion.jpg' WHERE crop_name = 'Onion';
UPDATE crops SET image_url = 'assets/images/crops/eggplant.jpg' WHERE crop_name = 'Eggplant';
UPDATE crops SET image_url = 'assets/images/crops/cabbage.jpeg' WHERE crop_name = 'Cabbage';
UPDATE crops SET image_url = 'assets/images/crops/cauliflower.jpg' WHERE crop_name = 'Cauliflower';
UPDATE crops SET image_url = 'assets/images/crops/guava.jpg' WHERE crop_name = 'Guava';
UPDATE crops SET image_url = 'assets/images/crops/pomegranate.jpg' WHERE crop_name = 'Pomegranate';
UPDATE crops SET image_url = 'assets/images/crops/pineapple.jpg' WHERE crop_name = 'Pineapple';
UPDATE crops SET image_url = 'assets/images/crops/litchi.jpg' WHERE crop_name = 'Litchi';
UPDATE crops SET image_url = 'assets/images/crops/jackfruit.jpg' WHERE crop_name = 'Jackfruit';
UPDATE crops SET image_url = 'assets/images/crops/sapota.jpg' WHERE crop_name = 'Sapota';
UPDATE crops SET image_url = 'assets/images/crops/custard_apple.jpg' WHERE crop_name = 'Custard Apple';
UPDATE crops SET image_url = 'assets/images/crops/fig.jpg' WHERE crop_name = 'Fig';
UPDATE crops SET image_url = 'assets/images/crops/ber.jpg' WHERE crop_name = 'Ber';
UPDATE crops SET image_url = 'assets/images/crops/amla.jpg' WHERE crop_name = 'Amla';
UPDATE crops SET image_url = 'assets/images/crops/muskmelon.jpg' WHERE crop_name = 'Muskmelon';
UPDATE crops SET image_url = 'assets/images/crops/watermelon.jpg' WHERE crop_name = 'Watermelon';
UPDATE crops SET image_url = 'assets/images/crops/plum.jpg' WHERE crop_name = 'Plum';
UPDATE crops SET image_url = 'assets/images/crops/peach.jpg' WHERE crop_name = 'Peach';
UPDATE crops SET image_url = 'assets/images/crops/pear.jpg' WHERE crop_name = 'Pear';
UPDATE crops SET image_url = 'assets/images/crops/okra.jpg' WHERE crop_name = 'Okra';
UPDATE crops SET image_url = 'assets/images/crops/carrot.jpg' WHERE crop_name = 'Carrot';
UPDATE crops SET image_url = 'assets/images/crops/spinach.jpg' WHERE crop_name = 'Spinach';
UPDATE crops SET image_url = 'assets/images/crops/fenugreek.jpg' WHERE crop_name = 'Fenugreek';
UPDATE crops SET image_url = 'assets/images/crops/bitter_gourd.jpg' WHERE crop_name = 'Bitter Gourd';
UPDATE crops SET image_url = 'assets/images/crops/bottle_gourd.jpg' WHERE crop_name = 'Bottle Gourd';
UPDATE crops SET image_url = 'assets/images/crops/ridge_gourd.jpg' WHERE crop_name = 'Ridge Gourd';
UPDATE crops SET image_url = 'assets/images/crops/sweet_potato.jpg' WHERE crop_name = 'Sweet Potato';
UPDATE crops SET image_url = 'assets/images/crops/radish.jpg' WHERE crop_name = 'Radish';
UPDATE crops SET image_url = 'assets/images/crops/cucumber.jpg' WHERE crop_name = 'Cucumber';
UPDATE crops SET image_url = 'assets/images/crops/pointed_gourd.jpg' WHERE crop_name = 'Pointed Gourd';
UPDATE crops SET image_url = 'assets/images/crops/ash_gourd.jpg' WHERE crop_name = 'Ash Gourd';
UPDATE crops SET image_url = 'assets/images/crops/pumpkin.jpg' WHERE crop_name = 'Pumpkin';
UPDATE crops SET image_url = 'assets/images/crops/cluster_bean.jpg' WHERE crop_name = 'Cluster Bean';
UPDATE crops SET image_url = 'assets/images/crops/nutmeg.jpg' WHERE crop_name = 'Nutmeg';
UPDATE crops SET image_url = 'assets/images/crops/cinnamon.jpg' WHERE crop_name = 'Cinnamon';
UPDATE crops SET image_url = 'assets/images/crops/mint.jpg' WHERE crop_name = 'Mint';
UPDATE crops SET image_url = 'assets/images/crops/curry_leaves.jpg' WHERE crop_name = 'Curry Leaves';
UPDATE crops SET image_url = 'assets/images/crops/black_cumin.jpg' WHERE crop_name = 'Black Cumin';
UPDATE crops SET image_url = 'assets/images/crops/oats.jpg' WHERE crop_name = 'Oats';
UPDATE crops SET image_url = 'assets/images/crops/foxtail_millet.jpg' WHERE crop_name = 'Foxtail Millet';
UPDATE crops SET image_url = 'assets/images/crops/barnyard_millet.jpg' WHERE crop_name = 'Barnyard Millet';
UPDATE crops SET image_url = 'assets/images/crops/cowpea.jpg' WHERE crop_name = 'Cowpea';
UPDATE crops SET image_url = 'assets/images/crops/horse_gram.jpg' WHERE crop_name = 'Horse Gram';
UPDATE crops SET image_url = 'assets/images/crops/almond.jpg' WHERE crop_name = 'Almond';
UPDATE crops SET image_url = 'assets/images/crops/walnut.jpg' WHERE crop_name = 'Walnut';
UPDATE crops SET image_url = 'assets/images/crops/pistachio.jpg' WHERE crop_name = 'Pistachio';
UPDATE crops SET image_url = 'assets/images/crops/mesta.jpg' WHERE crop_name = 'Mesta';
UPDATE crops SET image_url = 'assets/images/crops/bamboo.jpg' WHERE crop_name = 'Bamboo';
UPDATE crops SET image_url = 'assets/images/crops/vanilla.jpg' WHERE crop_name = 'Vanilla';
UPDATE crops SET image_url = 'assets/images/crops/saffron.jpg' WHERE crop_name = 'Saffron';
UPDATE crops SET image_url = 'assets/images/crops/betel_vine.jpg' WHERE crop_name = 'Betel Vine';
UPDATE crops SET image_url = 'assets/images/crops/aloe_vera.jpg' WHERE crop_name = 'Aloe Vera';
UPDATE crops SET image_url = 'assets/images/crops/cocoa.jpg' WHERE crop_name = 'Cocoa';
UPDATE crops SET image_url = 'assets/images/crops/chilli_pepper.jpg' WHERE crop_name = 'Chili Pepper';